orbs:
  android: circleci/android@0.2.1
  
jobs:
  build:
    node:
    docker:
      - image: circleci/node:latest
    environment:
      JVM_OPTS: -Xmx3200m
    description: |
      Start building an Android project on CircleCI
    executor:
      name: android
      sdk-version: "27"
    steps:
    - checkout
    - run: npm install
    - run:
        command: |
          sudo apt install default-jdk
          sudo apt update && sudo apt install android-sdk
          javac -version
          touch /home/circleci/project/android/local.properties
          echo "export ANDROID_SDK_ROOT=/opt/android-sdk/" >> /home/circleci/project/android/local.properties

    - run: cd android && ./gradlew assembleRelease
version: 2.1


