workflows:
  version: 2
  node-android-ios:
    jobs:
    - test
    - android:
        required:
        - test
        filters:
          branches:
            ignore:
              - master
              - staging
    
    - build_deploy_android_dev:
        filters:
          branches:
            only: master

    - build_deploy_android_staging:
        filters:
          branches:
            only: staging