orbs:
  android: circleci/android@0.2.1
  
jobs:
  build:
    node:
    docker:
      - image: circleci/node:latest
    environment:
      JVM_OPTS: -Xmx3200m
    description: |
      Start building an Android project on CircleCI
    steps:
    - checkout
    - run: npm install
    - run:
        command: |
          sudo apt install default-jdk

    - run: cd android && ./gradlew assembleRelease
version: 2.1


