
jobs:
  build:
    node:
    working_directory: ~/TestReactNative
    docker:
      - image: circleci/node:latest
    environment:
      JVM_OPTS: -Xmx3200m
    description: |
      Start building an Android project on CircleCI

    steps:
    - checkout
    - run: npm install
    - run:
        command: |
          sudo apt install default-jdk
          sudo apt update && sudo apt install android-sdk
          sudo npm install -g react-native-cli
          echo "sdk.dir=~/Android/Sdk/" >> ~/TestReactNative/android/local.properties
          npx jetify
          go get github.com/yelinaung/local-properties
          go install github.com/yelinaung/local-properties
          cd home/circleci/TestReactNative/android/
          local-properties

    - run: cd android && ./gradlew assembleRelease
    - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk

version: 2.1


