
jobs:
  build:
    node:
    working_directory: ~/TestReactNative
    docker:
      - image: circleci/node:latest
    environment:
      JVM_OPTS: -Xmx3200m
    description: |
      Start building an Android project on CircleCI

    steps:
    - checkout
    - run: npm install
    - run:
        command: |
          sudo apt install default-jdk
          sudo apt update && sudo apt install android-sdk

    - run: cd android && ./gradlew assembleRelease
    - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
version: 2.1


